services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:latest
    restart: unless-stopped
    container_name: wg-easy
    ports:
      - "51820:51820/udp"
      - "51880:51821/tcp"
    networks:
      wg:
        ipv4_address: 10.42.42.42
    volumes:
      - etc_wireguard:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      # - NET_RAW # ⚠️ Uncomment if using Podman Compose
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    environment:
      - INSECURE=true
      - PORT=51880
      #- HOST=192.168.1.57
      - WG_HOST=192.168.1.57

volumes:
  etc_wireguard:

networks:
  wg:
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: 10.42.42.0/24
