services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
      # Default HTTP Port
      - "5580:80/tcp"
      # Default HTTPs Port. FTL will generate a self-signed certificate
      # - "5443:443/tcp"
      # Uncomment the below if using Pi-hole as your DHCP Server
      #- "67:67/udp"
      # Uncomment the line below if you are using Pi-hole as your NTP server
      #- "123:123/udp"
    environment:
      # Set the appropriate timezone for your location https://en.wikipedia.org/wiki/List_of_tz_database_time_zones, e.g:
      TZ: 'America/New_York'
      # Set a password to access the web interface. Not setting one will result in a random password being assigned
      FTLCONF_webserver_api_password: ${gui_password}
      # If using Docker's default `bridge` network setting the dns listening mode should be set to 'all'
      FTLCONF_dns_listeningMode: 'all'
    volumes:
      - './etc-pihole:/etc/pihole'
    # See https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      # Optional, if Pi-hole should get some more processing time
      - SYS_NICE
      # to allow porting bindings below 1024 (needed for udp)
      - CAP_NET_BIND_SERVICE
      #- NET_ADMIN  # Required if you are using Pi-hole as your DHCP server, else not needed
      #- SYS_TIME   # Required if you are using Pi-hole as your NTP client to be able to set the host's system time
    restart: unless-stopped
